// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Groups struct {
	ID          int32   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Subtasks struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description *string          `json:"description"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Status      string           `json:"status"`
	TaskID      *int32           `json:"task_id"`
}

type Tasks struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description *string          `json:"description"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Status      string           `json:"status"`
	GroupID     *int32           `json:"group_id"`
	UserID      *int32           `json:"user_id"`
}

type UserGroups struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

type Users struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
