// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Groups, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtasks, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Tasks, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteGroup(ctx context.Context, id int32) error
	DeleteSubtask(ctx context.Context, id int32) error
	DeleteTask(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetGroup(ctx context.Context, id int32) (Groups, error)
	GetSubtask(ctx context.Context, id int32) (Subtasks, error)
	GetTask(ctx context.Context, id int32) (Tasks, error)
	GetUser(ctx context.Context, username string) (Users, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Groups, error)
	ListTaskSubtasks(ctx context.Context, taskID *int32) ([]Subtasks, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Tasks, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Groups, error)
	UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (Subtasks, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Tasks, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
